version: '3'
services:
    app:
        build:
            context: .
        command: /usr/src/app/start.sh
        depends_on:
            - postgres
        environment:
            JWT_SECRET: movie_theater_secret
            DATABASE_URL: postgres://postgres:your_password@postgres:5432/your_database_name
        volumes:
            - .:/usr/src/app
        ports:
            - '3000:3000'
        networks:
            - app-network
    redis:
        image: redis
        container_name: redis-container
        ports:
            - '6379:6379'
        networks:
            - app-network
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: your_password
            POSTGRES_DB: your_database_name
        ports:
            - '5432:5432'

networks:
    app-network:
        driver: bridge
